---
title: "group_condition"
format: pdf
editor: visual
---

```{r}
library(ggplot2)
library(dplyr)

library(readr)
dat <- shock_acuity_metrics_copy <- read_csv("shock_acuity_metrics copy.csv")
```

```{r}
dat <- dat %>%
  rename(
    id = "Participant",
    cond_name = "Condition",
    cond = "ConditionPercent",
    head_acc = "ProximalHighG2",
    leg_acc = "DistalHighG2",
    gap_size = "VisualAcuityPixels"
  ) %>% 
  mutate(cond = factor(cond))
```

#### Head Acceleration 

```{r}
str(dat)
head(dat)

r2_labels <- dat %>%
  group_by(cond) %>%
  summarise(
    r2 = summary(lm(gap_size ~ head_acc, data = cur_data()))$r.squared,
    head_acc = max(head_acc),
    pixel_size = max(gap_size) + 1
  ) %>%
  mutate(label = paste0(cond, ": R² = ", round(r2, 2)))

head_graph_cond <- ggplot(dat, aes(x = head_acc, y = gap_size, colour = cond)) +
  geom_point(size = 2, alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_text(
    data = r2_labels,
    aes(x = head_acc, y = pixel_size, label = label, colour = cond),
    size = 3,
    hjust = 1
  ) +
  labs(
    title = "Landolt ring gap vs. head acceleration by condition %",
    x = "Head acceleration (g)",
    y = "Landolt ring gap (pixels)"
  )





head_graph_cond_facet <- ggplot(dat, aes(x = head_acc, y = gap_size)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  facet_wrap(~ id, scales = "free") +
  labs(
    title = "Landolt ring gap vs. head acceleration by condition %",
    x = "Head acceleration (g)",
    y = "Landolt ring gap (pixels)"
  )



head_graph_cond_head
head_graph_cond_facet_head

```

#### Tibial acceleration

```{r}
str(dat)
head(dat)

r2_labels <- dat %>%
  group_by(cond) %>%
  summarise(
    r2 = summary(lm(gap_size ~ leg_acc, data = cur_data()))$r.squared,
    leg_acc = max(leg_acc),
    pixel_size = max(gap_size) + 1
  ) %>%
  mutate(label = paste0(cond, ": R² = ", round(r2, 2)))

leg_graph_cond <- ggplot(dat, aes(x = leg_acc, y = gap_size, colour = cond)) +
  geom_point(size = 2, alpha = 0.7) +
  geom_smooth(method = "lm", se = FALSE) +
  geom_text(
    data = r2_labels,
    aes(x = leg_acc, y = pixel_size, label = label, colour = cond),
    size = 3,
    hjust = 1
  ) +
  labs(
    title = "Landolt ring gap vs. tibial acceleration by condition %",
    x = "Tibial acceleration (g)",
    y = "Landolt ring gap (pixels)"
  )





leg_graph_cond_facet <- ggplot(dat, aes(x = leg_acc, y = gap_size)) +
  geom_point(alpha = 0.6) +
  geom_smooth(method = "lm", se = FALSE, color = "blue") +
  facet_wrap(~ id, scales = "free") +
  labs(
    title = "Landolt ring gap vs. tibial acceleration by condition %",
    x = "Tibial acceleration (g)",
    y = "Landolt ring gap (pixels)"
  )



leg_graph_cond
leg_graph_cond_facet
```
